---
- name: hello ansible ( date ... )
  hosts: managed_node
  user: ansible
  become: true

  tasks:
    - name: check id
      shell: (date; id) >>idlog.log
    - name: make directory
      file:
        path: "/tmp/ansible-study/child"
        state: directory
        owner: root
        group: daemon
        mode: 0750

